<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OcrAlphabetTrainer.Core\OcrAlphabetTrainer.Core.csproj" />
    <ProjectReference Include="..\OcrAlphabetTrainer.Model\OcrAlphabetTrainer.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SciSharp.TensorFlow.Redist" Version="2.3.1" />
  </ItemGroup>

</Project>
